"""Add support for multiple profiles and profile completion

Revision ID: 24ccac1313e0
Revises: 5022605d8ade
Create Date: 2025-05-03 14:59:19.904745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ccac1313e0'
down_revision = '5022605d8ade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename favorites table to favourites
    op.rename_table('favorites', 'favourites')
    
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id_fk', sa.Integer(), nullable=False),
    sa.Column('reported_user_id_fk', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reported_user_id_fk'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporter_id_fk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_complete', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')
        batch_op.drop_index('ix_users_username')
        batch_op.create_unique_constraint('uq_users_email', ['email'])
        batch_op.create_unique_constraint('uq_users_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_username', type_='unique')
        batch_op.drop_constraint('uq_users_email', type_='unique')
        batch_op.create_index('ix_users_username', ['username'], unique=1)
        batch_op.create_index('ix_users_email', ['email'], unique=1)

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('is_complete')

    op.drop_table('reports')
    
    # Rename favourites table back to favorites
    op.rename_table('favourites', 'favorites')
    # ### end Alembic commands ###
