"""Initial migration

Revision ID: 5022605d8ade
Revises: 
Create Date: 2025-05-01 12:56:26.769094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5022605d8ade'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('photo', sa.String(length=200), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_fk', sa.Integer(), nullable=False),
    sa.Column('fav_user_id_fk', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fav_user_id_fk'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id_fk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id_fk', 'fav_user_id_fk', name='unique_favorite')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_fk', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('parish', sa.String(length=100), nullable=False),
    sa.Column('biography', sa.Text(), nullable=False),
    sa.Column('sex', sa.String(length=20), nullable=False),
    sa.Column('race', sa.String(length=50), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('fav_cuisine', sa.String(length=100), nullable=False),
    sa.Column('fav_colour', sa.String(length=50), nullable=False),
    sa.Column('fav_school_subject', sa.String(length=100), nullable=False),
    sa.Column('political', sa.Boolean(), nullable=False),
    sa.Column('religious', sa.Boolean(), nullable=False),
    sa.Column('family_oriented', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id_fk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    op.drop_table('favorites')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
